### ISSUE TITLE
Helm chart debug enable doesn't work

### ISSUE THREAD

**Issue by gamer22026** [Orange-OpenSource/cassandra-k8s-operator#100]
The values.yaml specifies
```
debug:
  enable: false
```
but the deployment.yaml lists
```
{{- if .Values.debug }}
```

Maybe change to `debugEnable: false` in values.yaml and `{{- if .Values.debugEnable }}` in deployment.yaml to be consistent (there is an rbacEnable setting, for instance)

**Comment by cscetbon** [comment]
@gamer22026 I think we should simply do `{{- if .Values.debug.enabled }}`
