### ISSUE TITLE
runtime error when applying a change

### ISSUE THREAD

**Issue by cscetbon** [Orange-OpenSource/cassandra-k8s-operator#108]
The following steps produce a runtime error :
- k apply -f https://pastebin.com/raw/CPRsgqWk
- wait for the first node to be running (kgp -w)
- k apply -f https://pastebin.com/raw/N1YcpWMn

Here is a log of the runtime error https://pastebin.com/raw/5QPKYRwk

**Comment by mackwong** [comment]
N1YcpWMn has one more `gcStdout` than CPRsgqWk, so it lead to rack1 pod restart 
and `dcRackStatus.Phase` turn into `Pending`. 
```golang
if dcRackStatus.Phase != api.ClusterPhaseRunning ||
				(dcRackStatus.CassandraLastAction.Status == api.StatusOngoing ||
					dcRackStatus.CassandraLastAction.Status == api.StatusFinalizing) {
				logrus.WithFields(logrus.Fields{"cluster": cc.Name,
					"dc-rack": dcRackName}).Infof("Waiting Rack to be running before continuing, " +
					"we break ReconcileRack after updated statefulset")
				return nil
			}
```

**Comment by cscetbon** [comment]
@mackwong Can you add a unit test to prove it works as expected ? But I understand your point.

Thanks !
