### ISSUE TITLE
Cassandra Cluster Pod always use the configuration CASSANDRA_AUTHENTICATOR=PasswordAuthenticator

### ISSUE THREAD

**Issue by Saifulbappi** [Orange-OpenSource/cassandra-k8s-operator#118]
I am checking this operator and also new to kubernetes.
Whenever i create a cluster with config map cassandra-configmap-v1 given in the samples folder with changing field --
authenticator: AllowAllAuthenticator and 
authorizer: AllowAllAuthorizer .. 
pod is not taking these values.  when i log the pod, always showing  this--

`Starting Cassandra on 10.244.0.168
Configuration used :
CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
CASSANDRA_AUTHORIZER=CassandraAuthorizer`

i've checked the yaml in /etc/cassandra/cassandra.yaml .. it's showing the config file change has happened .. but it seems- the pod is not taking the configuration from /etc/cassandra/cassandra.yaml

**Comment by allamand** [comment]
Hi @Saifulbappi, 

this is configured from env var from the run.sh script : https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/sidecar/docker/bootstrap/files/run.sh, or it takes the default value from the file.

What did you do to change the value ?

**Comment by Saifulbappi** [comment]
hi @allamand  thanks for your reply. 
I have changed in configmap - cassandra-configmap-v1
at this lines -
 authenticator: AllowAllAuthenticator
 authorizer: AllowAllAuthorizer
in the cassandra.yaml portion. Nothing happened. Also i've tried to change these values with sed command in prerun.sh--
```
sed -i 's/authenticator: PasswordAuthenticator/authenticator: AllowAllAuthenticator/' /etc/cassandra/cassandra.yaml
 sed -i 's/authorizer: CassandraAuthorizer/authorizer: AllowAllAuthorizer/' /etc/cassandra/cassandra.yaml
```
    
 But pod didn't get these values
i've also checked - after making the changes-  '/etc/cassandra/cassandra.yaml' file in pod has the changed values in authenticator: and authorizer: key values. But the log shows it takes the default values-- CASSANDRA_AUTHENTICATOR=PasswordAuthenticator CASSANDRA_AUTHORIZER=CassandraAuthorizer. Also at the start of pod starting these logs shows

```
We have a ConfigMap, we surcharge default configuration files
'/tmp/cassandra/configmap/cassandra.yaml' -> '/etc/cassandra/cassandra.yaml'
'/tmp/cassandra/configmap/jvm.options' -> '/etc/cassandra/jvm.options'
'/tmp/cassandra/configmap/pre_run.sh' -> '/etc/cassandra/pre_run.sh'
```
Could you kindly tell me how can i change the values in cassandra.yaml value and pod get these values instead of default_values?

**Comment by allamand** [comment]
@Saifulbappi I've made some tests and i'm able to change this values by using the `pre_run.sh`script.

But in the last release we have introduce Init-containers that allows you to use other Cassandra image, such as default `cassandra:3.11` which has different default value for CASSANDRA_AUTHENTICATOR.

Can you please test again using latest release ?

**Comment by allamand** [comment]
@Saifulbappi now we uses by default official cassandra docker image which has all authenticator by default.

I uses the pre_run.sh script to change it ex:

```
apiVersion: v1
kind: ConfigMap
data:
  pre_run.sh: |-
    sed -i 's/authenticator: AllowAllAuthenticator/authenticator: PasswordAuthenticator/' /etc/cassandra/cassandra.yaml
    sed -i 's/authorizer: AllowAllAuthorizer/authorizer: CassandraAuthorizer/' /etc/cassandra/cassandra.yaml
    echo "** end of pre_run.sh script, continue with run.sh"

```
