### ISSUE TITLE
Tolerations Support

### ISSUE THREAD

**Issue by kri5** [Orange-OpenSource/cassandra-k8s-operator#136]
It would be very interesting to be able to support tolerations in order to schedule cassandra workloads only on some dedicated nodes (in combination with nodeselector).

What would be required to do so?

**Comment by allamand** [comment]
Hi @kri5, I’ve recently added a pod section in CassandraClister spec to add pod annotations **spec.pod.annotations**.  maybe we can specify some tolerations here that would be propagated to statefulset in generator.go

**Comment by mackwong** [comment]
If we add `podtemplate` section in CassandraCluster spec, then user can add everything, not just Tolerations. Is this better?
