### ISSUE TITLE
Adding Seedlist under Spec for manual / multicasskop seedlist management

### ISSUE THREAD

**Issue by fdehay** [Orange-OpenSource/cassandra-k8s-operator#144]
If someone (or multicasskop)  wants to manage the seedlist manually, one has to specify it under the Status part of the Cassandra cluster definition file. Normally, le status part is managed by casskop as part of the run so to specify something there seems illogical
Shouldn't we add a seedlist in the spec part to be the expected seedlist when the status one will contain the calculated one?

**Comment by jal06** [comment]
The seedless is managed automatically by CassKop (or multiCassKop). IMHO, there is no reason to update it manually.
