### ISSUE TITLE
Unable to connect reaper

### ISSUE THREAD

**Issue by Jabbl** [Orange-OpenSource/cassandra-k8s-operator#150]
After upgrading operator to 0.4.1 and setting up a new cluster, it seems the JMX-port isn't open to the outside, which means Reaper is unable to connect to the cluster.

I have executed this command on my two clusters, one launched with 0.3.1 that will soon be deprecated, and one launched with 0.4.1.\
The one from 0.3.1 lies in the `cassandra-operator` namespace, while 0.4.1 lies in the `cassandra` namespace. Both clusters are named `cassandra`:
``` bash
# First testing port 9042 as a baseline
# Old cluster
kubectl exec -it busybox -- nc -zvw2 cassandra.cassandra-operator 9042
> cassandra.cassandra-operator (10.42.1.2:9042) open

# New cluster
 kubectl exec -it busybox -- nc -zvw2 cassandra.cassandra 9042
> cassandra.cassandra (10.42.19.7:9042) open

# Actual test of JMX-port
# Old cluster
kubectl exec -it busybox -- nc -zvw2 cassandra.cassandra-operator 7199
> cassandra.cassandra-operator (10.42.1.2:7199) open

# New cluster
kubectl exec -it busybox -- nc -zvw2 cassandra.cassandra 7199
> command terminated with exit code 1
```

As far as I can see, both clusters are configured the same, and both kubernetes services have the same ports configured, but one can be reached while the other cannot.\
The commands `nodetool status` and such still work though, so I'm unsure of what's happening here.

**Comment by allamand** [comment]
Hi Philip,

which version of bootstrapImage did you uses ?

the jmx is configured using this file : https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/2f13639c07f8da485ee246796766897852f6e9d6/docker/bootstrap/files/cassandra-env.sh#L249 

actually last one is orangeopensource/cassandra-bootstrap:0.1.2

thanks

**Comment by Jabbl** [comment]
The bootstrap-image seems to be the latest:
```
bootstrap:
    Image:          orangeopensource/cassandra-bootstrap:0.1.2
```

How do I check if the JMX is configured to be local?

**Comment by allamand** [comment]
Hi,

If you exec inside the pod you can check with `ps aux`.

in my case the ouput contains:  `-Dcassandra.jmx.local.port=7199` so it listen only in local.

It seams that in our boostrap we force it to local : https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/master/docker/bootstrap/files/run.sh#L199-L205

but can't see why it was working before. @cscetbon any though on this ?

**Comment by allamand** [comment]
@Jabbl, note that you can change this using the post_run.sh script of the configMap in your pod https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/master/samples/cassandra-configmap-v1.yaml#L18-L20 (using sed..)

**Comment by Jabbl** [comment]
It seems that the output does contain `-Dcassandra.jmx.local.port=7199`, so I see why it doesn't work.

Using `sed`; what file do I change, and what should I change it to?\
I would expect something like `sed -i 's/-Dcassandra.jmx.local.port=7199/<something else>/'  <filename>`, but what should `<something else>` and `<filename>` be?

**Comment by allamand** [comment]
Sorry I’m on my phone.

The bootstrap build cassandra-env.sh so I think you can try to sed modify this file to enable jmx. Sorry don’t have valid example for now, maybe @cscetbon could help ?

**Comment by cscetbon** [comment]
I’ll take a look and let you know @Jabbl

**Comment by cscetbon** [comment]
@Jabbl I can confirm I see the same issue. We set CASSANDRA_ENABLE_JMX to True which is supposed to set LOCAL_JMX to no and prevent this from happening. However, with the new bootstrap image, it doesn't do what it used to do.
How critical is that issue for you ? I'll be working on a fix this week. 
FYI, The issue comes from the fact we set the environment variable to be used later but as it happens in a different container it does not work as before. To be fixed ...

In the meantime you can use a configmap to set a post-run action using something like 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap-post-run
data:
  post_run.sh: |-
    sed -I -e 's/"yes"/"notatall"/' /etc/cassandra/cassandra-env.sh
```
You need to assign that configmap to your cassandracluster object. It will just prevent setting the local.port for jmx, and make it available to the outside.

**Comment by Jabbl** [comment]
@cscetbon It isn't too large of an issue. My intention was to set up reaper before we sent any data to the cluster, though I don't expect the data going to shit that early.\
I'm probably going to test the `post_run.sh` workaround anyways, to see if anything else in my setup is wrong.

**Comment by Jabbl** [comment]
By the way, if the script that runs `test.sh` uses `source test.sh` instead of just `./test.sh`, all exported variables within the script will also be accessible in the caller and all it's children.

Example:\
test.sh:
```sh
export VARIABLE=true
```

caller.sh:
```sh
./test.sh
echo "Variable has value '$VARIABLE'"

source test.sh
echo "Variable has value '$VARIABLE'"
```
```sh
./caller.sh
> Variable has value ''
> Variable has value 'true'
```

Not sure if this is the method you will want to use, but it could be something to look at

**Comment by cscetbon** [comment]
Unfortunately this method is not suitable cause we're talking about 2 different containers and not just 2 different scripts. But I'm testing a fix atm.
