### ISSUE TITLE
Helm chart tags problems

### ISSUE THREAD

**Issue by hkroger** [Orange-OpenSource/cassandra-k8s-operator#17]
The "label" key is twice and labels are indented wrong here: https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/1f38e76fa377f63071b33748628a768795854398/helm/cassandra-operator/templates/service.yaml#L8

I think here the indentation is wrong (4 spaces instead of 2) for labels: https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/1f38e76fa377f63071b33748628a768795854398/helm/cassandra-operator/templates/rolebinding.yaml#L6

I think this should also have labels (if I install operator with helm chart, uninstall it and install again the CRD given an error because it already exists): https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/1f38e76fa377f63071b33748628a768795854398/helm/cassandra-operator/templates/db_v1alpha1_cassandracluster_crd.yaml#L3

**Comment by allamand** [comment]
Hi @hkroger,

for the crd problem on reinstall this must be manage via the --no-hooks flag cf https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/master/helm/cassandra-operator/readme.md#install-of-the-crd
