### ISSUE TITLE
Building from source fails when go modules is enabled

### ISSUE THREAD

**Issue by jsanda** [Orange-OpenSource/cassandra-k8s-operator#30]
I had been struggling to build from source. `make build` fails with:

```
go: error loading module requirements
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-gcflags", "all=-trimpath=${GOPATH}", "-asmflags", "all=-trimpath=${GOPATH}", "-o", "/Users/jsanda/Development/gocode/src/github.com/jsanda/cassandra-k8s-operator/build/_output/bin/cassandra-k8s-operator", "github.com/jsanda/cassandra-k8s-operator/cmd/manager"}: exit status 1)
Usage:
  operator-sdk build <image> [flags]

Flags:
      --docker-build-args string     Extra docker build arguments as one string such as "--build-arg https_proxy=$https_proxy"
      --enable-tests                 Enable in-cluster testing by adding test binary to the image
  -h, --help                         help for build
      --namespaced-manifest string   Path of namespaced resources manifest for tests (default "deploy/operator.yaml")
      --test-location string         Location of tests (default "./test/e2e")

make: *** [build] Error 1
```

When I scrolled up in the output I noticed:

`go: github.com/peterbourgon/diskv@v0.0.0-20190425080511-0be1b92a6df0: go.mod has post-v0 module path "github.com/peterbourgon/diskv/v3" at revision 0be1b92a6df0`

I am able to avoid this problem by explicitly disabling go modules:

```
$ export GO111MODULE=off
```

I played around with trying to get the build to work with modules enabled but was having mixed success. 

I think it would be helpful to do the following:

1) Make it explicit in the developer guide that go modules are not supported (if in fact my findings are correct)

2) Create a ticket for migrating to go modules

**Comment by cscetbon** [comment]
What about `make docker-build` ? There were probably changes that are not supported by the version you have for some reason

**Comment by jsanda** [comment]
`make docker-build` did work. My goal was to be able run some of the e2e tests, and I have had some success!

**Comment by allamand** [comment]
You are right, we did not support go modules at this time, your points 1 and 2 need to be treated.

**Comment by allamand** [comment]
see #40 for point 2

**Comment by cscetbon** [comment]
I propose we close that issue as there is already one to support Go modules. this way we even won't have to add it to the documentation. There is also still a way to build using our docker images
