### ISSUE TITLE
Update the service

### ISSUE THREAD

**Issue by allamand** [Orange-OpenSource/cassandra-k8s-operator#41]
Actually, we have 1 service for each dc defined in the CassandraCluster.

We want to change to have only one service for the entire cluster.

Application clients will needs do specify on which Cassandra DC they want to connect when establishing the connection.

**Comment by jsanda** [comment]
@allamand I would be happy to work on this. I can spend some time on it over the weekend.

**Comment by allamand** [comment]
yes thanks :)

**Comment by jsanda** [comment]
@allamand should there be a single monitoring service for the entire cluster as well?

**Comment by allamand** [comment]
@jsanda yes for monitoring too

**Comment by jsanda** [comment]
> Application clients will needs do specify on which Cassandra DC they want to connect when establishing the connection.

This would be done by using a `DCAwareRoundRobinPolicy` for the `LoadBalaningPolicy` right?

**Comment by jsanda** [comment]
Are there are any other changes needed for this PR? If not, do you want me to squash the commits?

**Comment by jsanda** [comment]
@allamand can this be closed?
