### ISSUE TITLE
the function name "isStatefulSetReady" is confusing

### ISSUE THREAD

**Issue by mackwong** [Orange-OpenSource/cassandra-k8s-operator#45]
https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/b29202cb98191a7af01f703273a90a5e089b8b07/pkg/controller/cassandracluster/statefulset.go#L256

This function name “ isStatefulSetReady” is confusing.
According to my understanding, he should be "isStatefulSetUnReady".

**Comment by allamand** [comment]
Hi @mackwong you're right :) thanks!
