### ISSUE TITLE
Set spec.resources.limits to spec.resources.requests when not defined

### ISSUE THREAD

**Issue by cscetbon** [Orange-OpenSource/cassandra-k8s-operator#67]
If **spec.resources.limits** is not set, cassandra pods can consume far more resources than expected and cause issues. It's easy to test it locally in a dind cluster and see that when a second node joins CPU sky rocks. The goal of this ticket is to set it to **spec.resources.requests** if it's not defined to avoid such a situation.

**Comment by jsanda** [comment]
What if `spec.resources.requests` is not set? I am currently using a GKE cluster and there is a LimitRange that specifies defaults for cpu, but there are no defaults for memory. I need to do some more reading, but I am inclined to say that in absence of anything else, memory defaults will come from cgroups.

**Comment by Orange-cscetbon** [comment]
I don't think we should ever accept a`CassandraCluster` object where spec.resources.requests is not set. @allamand wdyt ? If it's not the case we should definitely add it in the current code change I'm asking.

**Comment by jsanda** [comment]
I will work on this. Can someone assign it to me?

**Comment by cscetbon** [comment]
@jsanda let us know if you need any guiding.

**Comment by jsanda** [comment]
@cscetbon can this be closed?
